services:
  postgres:
    image: postgres:16.4-alpine@sha256:5660c2cbfea50c7a9127d17dc4e48543eedd3d7a41a595a2dfa572471e37e64c
    environment:
      POSTGRES_DB: writeleash
      POSTGRES_USER: writeleash_admin
      POSTGRES_PASSWORD: writeleash_admin_experiment_only
    ports:
      - "127.0.0.1:55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U writeleash_admin -d writeleash"]
      interval: 1s
      timeout: 5s
      retries: 30
