<?php
// #167 extends the existing authenticated HTTP harness; real filter_input/nonce/session transport.
$http_home167 = admin_get( $bulk_url );
$http_form167 = forms_for_action( $http_home167['body'], 'writeleash_free_preview' )[0];
$http_ajax167 = array( 'action' => 'writeleash_free_discovery', 'nonce' => $http_form167['discovery_nonce'], 'term' => $tag, 'page' => '1', 'kind' => 'products' );
$http_found167 = http_request( 'GET', admin_url_abs( '/wp-admin/admin-ajax.php' ), $http_ajax167 );
$http_data167 = json_decode( $http_found167['body'], true );
beq( $http_found167['code'], 200, 'discovery is authenticated real HTTP GET' );
bok( true === $http_data167['success'] && count( $http_data167['data']['results'] ) <= 20, 'HTTP discovery bounded with correct JSON shape' );
$http_bad167 = http_request( 'GET', admin_url_abs( '/wp-admin/admin-ajax.php' ), array_merge( $http_ajax167, array( 'nonce' => 'bad' ) ) );
beq( $http_bad167['code'], 403, 'HTTP invalid discovery nonce refused' );
$http_post167 = http_post( admin_url_abs( '/wp-admin/admin-ajax.php' ), $http_ajax167 );
beq( $http_post167['code'], 403, 'HTTP discovery POST cannot create work' );
$http_inputs167 = array_merge( $http_form167, array( 'product_ids' => array_map( 'strval', array_slice( $ids, 0, 2 ) ), 'selector' => 'ids', 'operation' => 'SET', 'product_search' => $tag, 'selection_action' => 'update-products', 'amount' => 'invalid-amount' ) );
unset( $http_inputs167['product_ids[]'] );
$http_update167 = http_post( $bulk_url, $http_inputs167 );
beq( $http_update167['code'], 200, 'native selection is a read-only same-page POST' );
bok( str_contains( $http_update167['body'], 'value="invalid-amount"' ), 'native POST retains operation input' );
a11y_check( $http_update167['body'], 'native selection' );
unset( $http_inputs167['selection_action'] );
$http_invalid167 = http_post( admin_url_abs( '/wp-admin/admin-post.php' ), $http_inputs167 );
$http_recovery167 = admin_get( (string) $http_invalid167['location'] );
bok( str_contains( $http_recovery167['body'], 'value="invalid-amount"' ) && str_contains( $http_recovery167['body'], 'Remove ' ), 'real preview PRG validation retains bounded session-scoped selection/configuration' );
$http_inputs167['amount'] = '80.00';
$http_preview167 = http_post( admin_url_abs( '/wp-admin/admin-post.php' ), $http_inputs167 );
bok( preg_match( '/wl_view=preview&wl_job=([0-9a-f-]{36})/', (string) $http_preview167['location'], $http_match167 ) === 1, 'picker POST imports explicit IDs into saved preview' );
$http_saved167 = admin_get( (string) $http_preview167['location'] );
bok( str_contains( $http_saved167['body'], 'changing 2' ), 'two selected IDs, not all discovery matches' );
login_session();
$http_recent167 = admin_get( $bulk_url );
bok( str_contains( $http_recent167['body'], 'Continue review' ) && str_contains( $http_recent167['body'], 'wl_view=preview' ), 'fresh authenticated session has continuation link' );
$http_status167 = admin_get( admin_url_abs( '/wp-admin/admin.php?page=writeleash-bulk-prices&wl_view=job&wl_job=' . $http_match167[1] ) );
bok( str_contains( $http_status167['body'], 'Continue review' ), 'direct HTTP status has continuation' );
$http_reopen167 = admin_get( (string) $http_preview167['location'] );
bok( str_contains( $http_reopen167['body'], '100.00' ) && str_contains( $http_reopen167['body'], '80.00' ), 'saved review retains original prices after fresh login' );
$http_products167 = admin_get( admin_url_abs( '/wp-admin/edit.php?post_type=product' ) );
bok( ! str_contains( $http_products167['body'], 'free-selection.js' ), 'selection asset never enqueued on stock Products screen' );
global $wl111_jar;
$http_jar167 = $wl111_jar; $wl111_jar = array();
$http_anon167 = http_request( 'GET', admin_url_abs( '/wp-admin/admin-ajax.php' ), $http_ajax167 );
bok( 200 !== $http_anon167['code'] && ! str_contains( $http_anon167['body'], '"results"' ), 'anonymous request cannot reuse nonce/discover products' );
$wl111_jar = $http_jar167;
echo "#167 real HTTP discovery/native selection/session recovery/saved-review continuity: PASS\n";
