<?php
/** #206 real WP/Woo leg; included by the existing two-engine/default/Redis Admin suite. */
use WriteLeash\Free_Admin as Admin;
use WriteLeash\Job_Repository as Repo;
wp_set_current_user( 1 );
$tag206 = 'WL206-' . wp_generate_uuid4();
$root206 = wp_insert_term( $tag206 . ' Parent', 'product_cat' )['term_id'];
$child206 = wp_insert_term( $tag206 . ' Child', 'product_cat', array( 'parent' => $root206 ) )['term_id'];
$grand206 = wp_insert_term( $tag206 . ' Grandchild', 'product_cat', array( 'parent' => $child206 ) )['term_id'];
$empty206 = wp_insert_term( $tag206 . ' Empty', 'product_cat' )['term_id'];
$direct206 = make_product( '100.00', 'publish', array( 'category' => $root206 ) );
$overlap206 = make_product( '100.00', 'publish', array( 'category' => $root206 ) );
wp_set_object_terms( $overlap206, array( $root206, $child206, $grand206 ), 'product_cat' );
$nested206 = make_product( '100.00', 'publish', array( 'category' => $grand206 ) );
$variable206 = new WC_Product_Variable(); $variable206->set_name( $tag206 . ' Variable' ); $variable206->set_status( 'publish' ); $variable206->set_category_ids( array( $child206, $grand206 ) ); $parent206 = $variable206->save();
$children206 = array();
for ( $i206 = 0; $i206 < 2; ++$i206 ) { $variation206 = new WC_Product_Variation(); $variation206->set_parent_id( $parent206 ); $variation206->set_status( 'publish' ); $variation206->set_regular_price( '100.00' ); $children206[] = $variation206->save(); }
WC_Product_Variable::sync( $parent206 );
$count_post206 = preview_post( array( 'selector' => 'category', 'category' => (string) $root206, 'selection_action' => 'count-targets', 'discovery_nonce' => wp_create_nonce( WriteLeash\Product_Discovery::ACTION ), 'amount' => 'invalid-amount' ) );
$jobs206 = (int) $wpdb->get_var( 'SELECT COUNT(*) FROM ' . WriteLeash\Job_Schema::jobs_table( $wpdb ) );
$count206 = Admin::process_selection( $count_post206, 'POST' );
eq( $count206['status'], 'OK', '#206 direct count authenticated read' );
eq( $count206['form']['selection_count']['selected'], 2, '#206 direct members only default, overlap once' );
$count_post206['include_subcategories'] = '1';
$count206 = Admin::process_selection( $count_post206, 'POST' );
eq( $count206['form']['selection_count'], array( 'selected' => 5, 'unreadable' => 0, 'missing' => 0 ), '#206 nested expansion and overlap count matches actual targets' );
eq( $count206['form']['include_subcategories'], '1', '#206 count retains toggle' );
eq( $count206['form']['amount'], 'invalid-amount', '#206 count independent of operation validation' );
eq( (int) $wpdb->get_var( 'SELECT COUNT(*) FROM ' . WriteLeash\Job_Schema::jobs_table( $wpdb ) ), $jobs206, '#206 count creates no job' );
$html206 = ( static function ( $form ) { ob_start(); Admin::render_view( '', '', 0, $form ); return ob_get_clean(); } )( $count206['form'] );
ok( str_contains( $html206, 'At last check: 5 deduplicated price targets' ) && str_contains( $html206, 'Counts are informational' ), '#206 native count and non-authority explained' );
$stale_added206 = make_product( '100.00', 'publish', array( 'category' => $grand206 ) );
$preview_post206 = array_merge( $count_post206, array( 'amount' => '80.00', 'selection_count' => array( 'selected' => 1 ) ) );
$preview206 = Admin::process_preview( $preview_post206, 'POST' );
eq( $preview206['status'], 'OK', '#206 Preview independent of stale or forged count' );
$job206 = Repo::read_by_public_id( $preview206['public_id'] ); $plan206 = Repo::hydrate_plan( $job206 );
$expected206 = array_merge( array( $direct206, $overlap206, $nested206, $stale_added206 ), $children206 ); sort( $expected206, SORT_NUMERIC );
eq( $plan206->data()['resolved_product_ids'], $expected206, '#206 Preview freezes newly resolved deduplicated IDs' );
eq( $plan206->data()['selection']['include_children'], true, '#206 durable hashed plan retains category scope' );
ok( str_contains( render_view( 'preview', $job206['public_id'], 0 ), 'direct members and all nested subcategories' ), '#206 review discloses frozen descendant scope' );
$late206 = make_product( '100.00', 'publish', array( 'category' => $grand206 ) );
eq( Repo::hydrate_plan( Repo::read( (int) $job206['id'] ) )->data()['resolved_product_ids'], $expected206, '#206 later category additions cannot enlarge saved plan' );
eq( Admin::process_approve( approve_post( $job206 ), 'POST' )['status'], 'OK', '#206 exact saved plan approved' );
run_job_terminal( (int) $job206['id'] );
foreach ( $expected206 as $id206 ) { price_eq( fresh_price( $id206 ), '80.00', '#206 frozen target applied' ); }
price_eq( fresh_price( $late206 ), '100.00', '#206 execution never reselects live category' );
$direct_plan206 = Admin::process_preview( preview_post( array( 'selector' => 'category', 'category' => (string) $root206, 'amount' => '80.00' ) ), 'POST' );
$old206 = Repo::hydrate_plan( Repo::read_by_public_id( $direct_plan206['public_id'] ) );
$old_bytes206 = $old206->json();
eq( WriteLeash\Change_Plan::hydrate( json_decode( $old_bytes206, true ) )->json(), $old_bytes206, '#206 historical direct material/hash hydration unchanged' );
eq( $old206->data()['selection']['include_children'], false, '#206 unchecked historical/default scope false' );
ok( str_contains( render_view( 'preview', $direct_plan206['public_id'], 0 ), 'direct members only; subcategories are not included' ), '#206 direct scope visible in saved review' );
$empty_post206 = array_merge( $count_post206, array( 'category' => (string) $empty206 ) );
eq( Admin::process_selection( $empty_post206, 'POST' )['form']['selection_count']['selected'], 0, '#206 empty category count explained' );
$deny206 = static function ( $caps, $cap, $actor, $args ) use ( $nested206 ) { return 'edit_post' === $cap && (int) ( $args[0] ?? 0 ) === $nested206 ? array( 'do_not_allow' ) : $caps; };
add_filter( 'map_meta_cap', $deny206, 10, 4 );
eq( Admin::process_selection( $count_post206, 'POST' )['reason'], 'permission_denied', '#206 denied target refuses population disclosure' );
remove_filter( 'map_meta_cap', $deny206, 10 );
WriteLeash\Price_Cache_Verifier::invalidate( $nested206 );
$unreadable206 = static function ( $class, $type, $post_type, $id ) use ( $nested206 ) { if ( (int) $id === $nested206 ) { throw new RuntimeException( 'test unreadable category target' ); } return $class; };
add_filter( 'woocommerce_product_class', $unreadable206, 10, 4 );
eq( Admin::process_selection( $count_post206, 'POST' )['form']['selection_count']['unreadable'], 1, '#206 unreadable target explained without disappearing' );
remove_filter( 'woocommerce_product_class', $unreadable206, 10 );
eq( Admin::process_selection( array_merge( $count_post206, array( 'discovery_nonce' => 'bad' ) ), 'POST' )['reason'], 'invalid_nonce', '#206 count rejects stale session nonce' );
eq( Admin::process_selection( $count_post206, 'GET' )['reason'], 'post_required', '#206 count strict POST' );
wp_set_current_user( 0 );
eq( Admin::process_selection( $count_post206, 'POST' )['status'], 'FORBIDDEN', '#206 anonymous count forbidden' );
wp_set_current_user( 1 );
$boundary206 = wp_insert_term( $tag206 . ' Boundary', 'product_cat' )['term_id'];
wp_defer_term_counting( true );
foreach ( $large167 as $id206 ) { wp_set_object_terms( $id206, array( $boundary206 ), 'product_cat' ); }
wp_defer_term_counting( false );
$limit_post206 = array_merge( $count_post206, array( 'category' => (string) $boundary206 ) );
eq( Admin::process_selection( $limit_post206, 'POST' )['form']['selection_count'], array( 'over_limit' => true ), '#206 1001 final category targets explained as over-limit' );
wp_set_object_terms( end( $large167 ), array(), 'product_cat' );
eq( Admin::process_selection( $limit_post206, 'POST' )['form']['selection_count']['selected'], 1000, '#206 1000 final category targets accepted' );
marker( '#206 nested categories, expanded target count, authorization, frozen execution and limits' );
